# Generated by Django 5.2.17 on 2026-09-01 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nome_admin', models.CharField(max_length=150)),
                ('email_admin', models.EmailField(max_length=100)),
                ('matricula', models.IntegerField()),
                ('data_nasc', models.DateField()),
                ('senha_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(blank=True, db_column='id_empresa', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='empresas.empresa')),
                ('fornecedor', models.ForeignKey(blank=True, db_column='id_fornecedor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='fornecedores.fornecedor')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
