# Generated by Django 6.1.1 on 2026-09-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_empresas', '0001_initial'),
        ('app_fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoProduto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_produtos', to='app_empresas.empresa')),
            ],
            options={
                'db_table': 'catalogo_produto',
                'unique_together': {('nome', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(max_length=50)),
                ('estoque_atual', models.IntegerField(default=0)),
                ('estoque_capacidade', models.IntegerField(default=0)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INSPECAO', 'Inspeção'), ('BLOQUEIO', 'Bloqueio')], default='ATIVO', max_length=10)),
                ('data_fabricacao', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ala', models.CharField(max_length=20)),
                ('secao', models.CharField(max_length=20)),
                ('prateleira', models.CharField(max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='app_produtos.catalogoproduto')),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app_empresas.empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_fornecidos', to='app_fornecedores.fornecedor')),
            ],
            options={
                'db_table': 'produto',
                'unique_together': {('lote', 'empresa')},
            },
        ),
    ]
