# Generated by Django 6.1.1 on 2026-09-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INSPECAO', 'Inspeção'), ('BLOQUEIO', 'Bloqueio'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=10),
        ),
    ]
