# Generated by Django 6.1.1 on 2026-09-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
