# Generated by Django 5.2.17 on 2026-09-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresas', '0001_initial'),
        ('app_produtos', '0002_produto_delete_tabelaa_delete_tabelab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='id_produtos',
            new_name='id',
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('lote', 'empresa')},
        ),
        migrations.AddField(
            model_name='produto',
            name='empresa',
            field=models.ForeignKey(db_column='id_empresa', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='app_empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='lote',
            field=models.CharField(default=240315, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
    ]
