# Generated by Django 5.2.17 on 2026-09-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produtos', models.AutoField(primary_key=True, serialize=False)),
                ('nome_prod', models.CharField(blank=True, max_length=150, null=True)),
                ('valor_prod', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=80, null=True)),
                ('quantidade_estoque', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.DeleteModel(
            name='TabelaA',
        ),
        migrations.DeleteModel(
            name='TabelaB',
        ),
    ]
