# Generated by Django 5.2.17 on 2026-09-22 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.IntegerField()),
                ('nome_admin', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='app_empresas.empresa')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
