# Generated by Django 6.1.1 on 2026-09-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nome_admin', models.CharField(max_length=150)),
                ('email_admin', models.EmailField(max_length=100)),
                ('matricula', models.IntegerField()),
                ('data_nasc', models.DateField()),
                ('senha_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='app_empresas.empresa')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
