# Generated by Django 5.2.17 on 2026-09-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
        ('app_empresas', '0001_initial'),
        ('app_fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='app_empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='fornecedor',
            field=models.ForeignKey(blank=True, db_column='id_fornecedor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='app_fornecedores.fornecedor'),
        ),
    ]
