# Generated by Django 6.1.1 on 2026-09-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0001_initial'),
        ('app_fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='fornecedor',
            field=models.ForeignKey(blank=True, db_column='id_fornecedor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='app_fornecedores.fornecedor'),
        ),
    ]
