# Generated by Django 5.2.17 on 2026-10-03 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_admin', '0001_initial'),
        ('app_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('TODOS', 'Todos'), ('FORNECEDOR', 'Fornecedor'), ('PRODUTO', 'Produto')], max_length=10)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('dados', models.JSONField(default=dict)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='app_empresas.empresa')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_admin.admin')),
            ],
            options={
                'db_table': 'relatorio',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
