# Generated by Django 6.1.1 on 2026-09-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social_fn', models.CharField(max_length=150)),
                ('nome_fantasia_fn', models.CharField(max_length=150)),
                ('cnpj_fn', models.CharField(max_length=18, unique=True)),
                ('cep', models.CharField(max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=150)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('email_fn', models.EmailField(max_length=100)),
                ('nome_responsavel', models.CharField(max_length=150)),
                ('telefone_fn', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='app_empresas.empresa')),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
    ]
