# Generated by Django 5.2.17 on 2026-09-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social_fn', models.CharField(max_length=150)),
                ('nome_fantasia_fn', models.CharField(max_length=150)),
                ('cnpj_fn', models.CharField(max_length=18)),
                ('endereco_fn', models.CharField(max_length=200)),
                ('telefone_fn', models.CharField(max_length=20)),
                ('email_fn', models.EmailField(max_length=100)),
                ('contato_resp', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
    ]
