# Generated by Django 5.2.17 on 2026-09-19 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_fornecedores', '0001_initial'),
        ('app_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecimentoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_produtos.produto'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='produtos',
            field=models.ManyToManyField(related_name='fornecedores', through='app_fornecedores.FornecimentoProduto', to='app_produtos.produto'),
        ),
        migrations.AlterUniqueTogether(
            name='fornecimentoproduto',
            unique_together={('fornecedor', 'produto')},
        ),
    ]
