# Generated by Django 5.2.17 on 2026-09-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresas', '0001_initial'),
        ('app_fornecedores', '0001_initial'),
        ('app_produtos', '0002_produto_delete_tabelaa_delete_tabelab'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='empresa',
            field=models.ForeignKey(db_column='id_empresa', default=240315, on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='app_empresas.empresa'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FornecimentoProduto',
            fields=[
                ('id_fornecimento', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, related_name='fornecimentos', to='app_empresas.empresa')),
                ('fornecedor', models.ForeignKey(db_column='id_fornecedor', on_delete=django.db.models.deletion.CASCADE, related_name='fornecimentos', to='app_fornecedores.fornecedor')),
                ('produto', models.ForeignKey(db_column='id_produto', on_delete=django.db.models.deletion.CASCADE, related_name='fornecimentos', to='app_produtos.produto')),
            ],
            options={
                'db_table': 'fornecimento_produto',
                'unique_together': {('fornecedor', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='produtos',
            field=models.ManyToManyField(related_name='fornecedores', through='app_fornecedores.FornecimentoProduto', to='app_produtos.produto'),
        ),
    ]
