# Generated by Django 5.2.17 on 2026-09-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_fornecedores', '0001_initial'),
        ('app_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='produtos',
            field=models.ManyToManyField(related_name='fornecedores', to='app_produtos.catalogoproduto'),
        ),
    ]
