# Generated by Django 5.2.17 on 2026-09-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social_emp', models.CharField(max_length=150)),
                ('nome_fantasia_emp', models.CharField(max_length=150)),
                ('cnpj_emp', models.CharField(max_length=18)),
                ('endereco_emp', models.CharField(max_length=200)),
                ('telefone_emp', models.CharField(max_length=20)),
                ('email_emp', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
